on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Publish NuGet Packages
    steps:

    # Checkout
    - name: Checkout repository
      uses: actions/checkout@v3

    # Setup .NET Core
    - name: Setup .NET Core @ Latest
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
        source-url: https://api.nuget.org/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NugetAuthToken}}

    # Build and pack
    - name: Build solution and generate NuGet package
      run: ./pack.sh

    # Push to NuGet
    - name: Push generated package to GitHub registry
      run: dotnet nuget push **/*.nupkg --skip-duplicate -k ${{ secrets.NugetAuthToken }}